name: Test

env:
  DENO_VERSION: v1.x

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - name: Lint
        run: deno lint --unstable

  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - name: Format
        run: |
          deno fmt
          git diff --exit-code

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - name: Test
        run: |
          deno test
