name: Test

env:
  DENO_VERSION: 1.x

on:
  schedule:
    - cron: "0 7 * * 0"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@main
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - name: Lint
        run: deno lint

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@main
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - name: Format
        run: |
          deno fmt --check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@main
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - name: Test
        run: |
          deno test
        timeout-minutes: 5

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@main
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - name: Type check
        run: |
          deno test --unstable --no-run ./*.ts
