name: udd

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  udd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1.x"
      - name: Install tools
        run: make tools
      - name: Update dependencies
        id: update
        run: echo "::set-output name=OUTPUT::$(make update)"
      - name: Commit changes
        run: |
          git config user.name '${{ github.actor }}'
          git config user.email '${{ github.actor }}@users.noreply.github.com'
          git commit -a -F- <<EOM
          :package: Update Deno dependencies

          ${{ steps.update.outputs.OUTPUT }}
          EOM
      - uses: peter-evans/create-pull-request@v3
        with:
          title: ":package: Update Deno dependencies"
          body: "${{ steps.update.outputs.OUTPUT }}"
          label: automation
          branch: automation/update-dependencies
          branch-suffix: timestamp
          delete-branch: true
          token: "${{ secrets.PA_TOKEN }}"
